[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "scikit-build",
    "cmake>=3.17",
    "nanobind",
    "ninja; platform_system!='Windows'"
]

build-backend = "setuptools.build_meta"
