name: "Pip"

on:
  workflow_dispatch:
  pull_request:
  #push:
  #  branches:
  #    - main

jobs:
  build:
    name: Build with Pip
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]
        python-version: ["3.8", "3.10"]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # Set up the Optitrack Camera SDK
    # https://s3.amazonaws.com/naturalpoint/software/OptiTrackCameraSDK/OptiTrack_Camera_SDK_2.3.1_Final.exe

    - name: Build and install
      run: python -m pip install pytest
           pip install --verbose .

    - name: Test
      run: python -m pytest
